docs/participants.md
=> Add participant

docs/participants.md
=> Add new participant

docs/participants.md
=> add_new_participant

terraform_aws/.github/workflows/terraform.yml, terraform_aws/.gitignore, terraform_aws/README.md, terraform_aws/main.tf, terraform_aws/outputs.tf, terraform_aws/terraform.tf, terraform_aws/variables.tf
=> Add terraform aws

terraform_gcp/.github/workflows/gcp-terraform_deploy_kubernetes.yml, terraform_gcp/.gitignore, terraform_gcp/README.md, terraform_gcp/terraform/backend.tf, terraform_gcp/terraform/main.tf, terraform_gcp/terraform/provider.tf, terraform_gcp/terraform/variables.tf
- github workflow (terraform apply/destroy by message in commit) files: gcp-terraform_deploy_kubernetes.yml
- terraform deploy K8s cluster in GCP (remote state - gc bucket) files: terraform_gcp/terraform/ backend.tf main.tf provider.tf variables.tf
-
-
-
=> Add new cloud for deploy (GCP)

.github/workflows/azure-pipeline.yml, terraform-azure/hello-world.yml, terraform-azure/main.tf, terraform-azure/outputs.tf, terraform-azure/scripts/create_storage.sh, terraform-azure/terraform.tfvars, terraform-azure/test, terraform-azure/variables.tf
=> azure-fixed-pipeline

.github/workflows/azure-pipeline.yml
=> test pipeline

.github/workflows/terraform.yml, terraform_aws/main.tf
=> add aws terraform

container.init.sh, docker-compose.yml
=> wp-team_added_docker_compose_with_db_wp-app_wp-cli_container-init

.github/workflows/azure-pipeline.yml, terraform-azure/providers.tf, terraform-azure/scripts/create_storage.sh, terraform-azure/scripts/install-tekton.sh
=> Tekton week2

.github/workflows/mysql.yml
=> test_mysql

.github/workflows/mysql.yml
=> test_myysql_pip

terraform_gcp/main.tf
=> Fix-git-action

.github/workflows/mysql.yml
=> fix_DDD_azure

terraform_gcp/backend.tf
=> Fix Lock TFstate

.github/workflows/azure-pipeline.yml, .github/workflows/mysql.yml, terraform-azure/mysql.yml
=> fix_pipeline_azure

.github/workflows/TerraformGCP.yml, terraform_gcp/Deploy.yml, terraform_gcp/README.md, terraform_gcp/main.tf, terraform_gcp/pipeline/clonebuildpush.yaml, terraform_gcp/pipeline/triger.yaml, terraform_gcp/scripts/add-webhook.sh, terraform_gcp/scripts/install-tekton.sh, terraform_gcp/scripts/setup-db-wp.sh, terraform_gcp/tekton/ingress.yaml, terraform_gcp/tekton/role.yaml, terraform_gcp/tekton/serviceaccount.yaml
=> add-tekton/readme

.github/workflows/TerraformGCP.yml, terraform_gcp/Deploy.yml, terraform_gcp/Dockerfile, terraform_gcp/README.md, terraform_gcp/backend.tf, terraform_gcp/main.tf, terraform_gcp/pipeline/clonebuildpush.yaml, terraform_gcp/pipeline/triger.yaml, terraform_gcp/scripts/install-tekton.sh, terraform_gcp/scripts/setup-db-wp.sh, terraform_gcp/variables.tf
=> full project test

README.md, docs/ReadmeAWS.md, docs/ReadmeAzure.md, docs/ReadmeGCP.md
=> Update Main or CloudReadme 

README.md, docs/ReadmeAWS.md, docs/ReadmeAzure.md, docs/ReadmeGCP.md
=> Documentation update

docs/participants.md
=> fixed_brokens_links_of_images_and_was_added_a_parcipant
